const title = document.getElementsByTagName("title")[0];
title.innerText = "Login Form";
const body = document.getElementsByTagName("body")[0];
const div = document.createElement("div");
div.classList.add("login-container");
body.appendChild(div);
const h1 = document.createElement("h1");
h1.innerText = "Log in";
div.appendChild(h1);
const p = document.createElement("p");
p.innerHTML = "New Here? <a href ='#'>Create a account....</a>";
div.appendChild(p);
const form = document.createElement("form");
div.appendChild(form);
const label1 = document.createElement("label");
label1.setAttribute("for", "username");
label1.innerText = "Username or Email";
form.appendChild(label1);
const input1 = document.createElement("input");
input1.setAttribute("type", "text");
input1.setAttribute("id", "username");
input1.setAttribute("name", "username");
input1.setAttribute("placeholder", "Username or Email");
form.appendChild(input1);
const label2 = document.createElement("label");
label2.setAttribute("for", "password");
label2.innerText = "Password";
form.appendChild(label2);
